language: haxe

haxe:
  - 3.4.7
 
env: 
  - TARGET=flash
  - TARGET=neko
  - TARGET=html5

install:
  - haxelib git flixel https://github.com/HaxeFlixel/flixel
  - cd ~/haxe/lib/flixel/git/tests
  - haxe RunTravis.hxml
  - neko RunTravis.n flash new -install
  - cd -
  - haxelib dev flixel-templates $TRAVIS_BUILD_DIR

script:
  - cd $HOME/haxe/lib/flixel-tools/git
  - haxe build.hxml
  - cd $TRAVIS_BUILD_DIR
  - haxelib run flixel-tools tpl -n "template"
  - cd template
  - haxelib run lime build $TARGET
