language: haxe
dist: xenial

haxe:
  - 3.4.7
  - development
 
env: 
  - TARGET=flash
  - TARGET=neko
  - TARGET=html5

install:
  - haxelib git flixel https://github.com/HaxeFlixel/flixel
  - haxe --cwd ~/haxe/lib/flixel/git/tests --run RunTravis flash new -install
  - haxelib dev flixel-templates .

script:
  - haxe --cwd ~/haxe/lib/flixel-tools/git build.hxml
  - haxelib run flixel-tools tpl -n "template"
  - cd template
  - haxelib run lime build $TARGET
